apiVersion: v1
kind: Namespace
metadata:
  name: leader-election-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-election-sa
  namespace: leader-election-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election
  namespace: leader-election-ns
  labels:
    app: leader-election
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election
  template:
    metadata:
      labels:
        app: leader-election
    spec:
      serviceAccountName: leader-election-sa
      containers:
      - name: leader-election
        image: <your-dockerhub-username>/k8s-python-leader-election:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LEASE_NAME
          value: "leader-election-lease"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LEASE_DURATION_SECONDS
          value: "15"
        - name: RENEW_INTERVAL_SECONDS
          value: "5"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - leader-election
              topologyKey: "kubernetes.io/hostname"
