apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-election-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election
  labels:
    app: leader-election
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election
  template:
    metadata:
      labels:
        app: leader-election
    spec:
      serviceAccountName: leader-election-sa
      containers:
      - name: leader-election
        image: <your-dockerhub-username>/k8s-python-leader-election:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        imagePullPolicy: Always
